tabs:
  main:
    display: Main
    sections:
      -
        fields:
          -
            handle: show_secondary_nav
            field:
              type: toggle
              display: 'Show Secondary Nav'
          -
            handle: secondary_nav_location
            field:
              options:
                top: Top
                off_canvas: 'Off Canvas'
              type: radio
              display: 'Secondary Nav Location'
              if:
                show_secondary_nav: 'equals true'
      -
        display: Analytics
        fields:
          -
            handle: enable_fathom
            field:
              type: toggle
              display: 'Enable Fathom'
              instructions: 'Enable Fathom Analytics script. Be sure to add your tracking ID to your .env file using FATHOM_SITE_ID. Works on Production environment only.'
              width: 33
          -
            handle: enable_ga4
            field:
              type: toggle
              display: 'Enable GA4'
              instructions: 'Enable GA4 script. Be sure to add your tracking ID to your .env file using GOOGLE_ANALYTICS_ID. Works on Production environment only.'
              width: 33
          -
            handle: enable_event_tracking
            field:
              type: toggle
              display: 'Enable Event Tracking'
              instructions: 'Add analytics event tracking to Fathom or GA.'
              if_any:
                enable_fathom: 'equals true'
                enable_ga4: 'equals true'
      -
        display: SEO
        fields:
          -
            import: seo_fields
